### ISSUE TITLE
Error while  running the microservice

### ISSUE THREAD

**Issue by bhargav-sudo** [dlstreamer/pipeline-server#102]
Hi I am receiving the following error by running the below command.

Building microservice has done successfully

**command** : ./docker/run.sh -v /tmp:/tmp/

**Error :** 

Found /dev/snd - enabling microphone

Running Video Analytics Serving Image: 'video-analytics-serving-gstreamer'
   Models: ''
   Pipelines: ''
   Framework: 'gstreamer'
   Environment: ''
   Volume Mounts: '-v /tmp:/tmp/ -v /dev/bus/usb:/dev/bus/usb '
   Mode: 'SERVICE'
   Ports: '-p 8080:8080 '
   Name: 'video-analytics-serving-gstreamer'
   Network: ''
   Entrypoint: ''
   EntrypointArgs: ''
   User: '--user 618207285'
   User Groups: '--group-add 44 --group-add audio --group-add users '
   Devices: '--device /dev/dri --device /dev/video0 --device /dev/video1 --device /dev/snd '
   Device CGroup Rule: '--device-cgroup-rule='c 189:* rmw''

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/video-analytics-serving/vaserving/__main__.py", line 9, in <module>
    import connexion
  File "/usr/local/lib/python3.8/dist-packages/connexion/__init__.py", line 5, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/dist-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/dist-packages/connexion/apis/abstract.py", line 17, in <module>
    from ..spec import Specification
  File "/usr/local/lib/python3.8/dist-packages/connexion/spec.py", line 7, in <module>
    import jinja2
  File "/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.8/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)

How to solve it..?
My markspace version 

![Screenshot from 2022-02-21 13-52-24](https://user-images.githubusercontent.com/57169077/154915740-c6612b7c-f95a-4d39-9bb7-7affa87bb105.png)

Thanks.

**Comment by brmarkus** [comment]
Looks like "https://github.com/dlstreamer/pipeline-server/issues/101", which says:

> Two workarounds:
> 
> 1. Use container from dockerhub: [intel/video-analytics-serving:0.7.0](https://hub.docker.com/r/intel/video-analytics-serving)
> 2. Update connexion version to 2.11.1 in [requirements.service.txt](https://github.com/dlstreamer/pipeline-server/blob/master/requirements.service.txt#L1) and re-build.

**Comment by bhargav-sudo** [comment]
OK. will check that and let you know.
Thanks

**Comment by bhargav-sudo** [comment]
Done. Working.
Updates connexion version.
Thanks.
